name       : subliminal
version    : 2.0.5
release    : 2
source     :
    - https://github.com/Diaoul/subliminal/archive/2.0.5.tar.gz : b956f02ae0286ad04be5bbf1c5570964aa17bb53c99fcce067e8334d99516ae2
license    : MIT
component  : programming
summary    : Subtitles, faster than your thoughts
description: |
    Python library to search and download subtitles.
rundeps    :
    - python-appdirs
    - python-beautifulsoup4
    - python-click
    - python-dogpile-cache
    - python-enzyme
    - python-guessit
    - python-pysrt
    - python-pytz
    - python-rarfile
    - python-stevedore
build      : |
    %python3_setup
install    : |
    %python3_install
