name       : subliminal
version    : 2.0.3
release    : 1
source     :
    - https://github.com/Diaoul/subliminal/archive/2.0.3.tar.gz : 12ad058d8bfdb0471d2021f8a486c2a11d2470e845bec1e71f698e4523ddc8fe
license    : MIT
component  : programming
summary    : Subtitles, faster than your thoughts.
description: |
    Subtitles, faster than your thoughts.
builddeps  :
    - python-setuptools
rundeps    :
    - python-appdirs
    - python-babelfish
    - python-beautifulsoup4
    - python-chardet
    - python-click
    - python-dogpile-cache
    - python-enzyme
    - python-futures
    - python-guessit
    - python-pysrt
    - python-pytz
    - python-rarfile
    - python-setuptools
    - python-stevedore
build      : |
    %python_setup
install    : |
    %python_install
